model_name: "gemini-1.5-flash"
generation_config:
  temperature: 1
  top_p: 0.95
  top_k: 64
  max_output_tokens: 8192
  response_mime_type: "application/json"
system_instruction_path:  config/system_instruction.txt
question_path: config/question.txt