
gemini: 
  model_name: "gemini-1.5-flash"
  generation_config:
    temperature: 1
    top_p: 0.95
    top_k: 64
    max_output_tokens: 8192
    response_mime_type: "application/json"

qwen2:
  model_name: models/qwen2/qwen2_vl_lora_sft_2b # can be path to local model
  min_pixels: 200_704 # 256*28*28
  max_pixels: 1_003_520 # 1280*28*28


system_instruction_path:  config/system_instruction.txt
question_path: config/question.txt
